CREATE TABLE Users (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Email NVARCHAR(100) NOT NULL UNIQUE,
    FirstName NVARCHAR(50) NOT NULL,
    LastName NVARCHAR(50) NOT NULL
);

CREATE TABLE Car (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Make NVARCHAR(50) NOT NULL,
    Model NVARCHAR(50) NOT NULL,
    Year INT NOT NULL,
    VIN NVARCHAR(17) NULL,
    OwnerId INT NOT NULL,
    CONSTRAINT FK_Car_Owner FOREIGN KEY (OwnerId) REFERENCES Users(Id)
);

CREATE TABLE CarAccess (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    CarId INT NOT NULL,
    UserId INT NOT NULL,
    GrantedDate DATETIME NOT NULL,
    ExpiryDate DATETIME NULL,
    CONSTRAINT FK_CarAccess_Car FOREIGN KEY (CarId) REFERENCES Car(Id) ON DELETE CASCADE,
    CONSTRAINT FK_CarAccess_User FOREIGN KEY (UserId) REFERENCES Users(Id) ON DELETE CASCADE
);

CREATE TABLE CarInsurance (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    CarId INT NOT NULL,
    Provider NVARCHAR(100) NOT NULL,
    PolicyNumber NVARCHAR(50) NOT NULL,
    StartDate DATETIME NOT NULL,
    EndDate DATETIME NOT NULL,
    CONSTRAINT FK_CarInsurance_Car FOREIGN KEY (CarId) REFERENCES Car(Id) ON DELETE CASCADE
);

CREATE TABLE CarIssue (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    CarId INT NOT NULL,
    Title NVARCHAR(200) NOT NULL,
    Description NVARCHAR(1000) NOT NULL,
    ReportedDate DATETIME NOT NULL,
    ResolvedDate DATETIME NULL,
    Status INT NOT NULL,
    Urgency INT NOT NULL,
    CONSTRAINT FK_CarIssue_Car FOREIGN KEY (CarId) REFERENCES Car(Id) ON DELETE CASCADE
);

CREATE TABLE CarService (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    CarId INT NOT NULL,
    Description NVARCHAR(200) NOT NULL,
    ServiceDate DATETIME NOT NULL,
    Mileage INT NULL,
    Cost DECIMAL(10,2) NOT NULL,
    Type INT NOT NULL,
    Notes NVARCHAR(500) NULL,
    CONSTRAINT FK_CarService_Car FOREIGN KEY (CarId) REFERENCES Car(Id) ON DELETE CASCADE
);

CREATE TABLE Notification (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    CarId INT NOT NULL,
    CarServiceId INT NOT NULL,
    NotifyAllUsers BIT NOT NULL,
    CONSTRAINT FK_Notification_Car FOREIGN KEY (CarId) REFERENCES Car(Id) ON DELETE CASCADE,
    CONSTRAINT FK_Notification_CarService FOREIGN KEY (CarServiceId) REFERENCES CarService(Id) ON DELETE CASCADE
);
